export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_EMAIL_ALREADY_IN_USED = 'SIGNUP_EMAIL_ALREADY_IN_USED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';
export const FETCH_CURRENT_USER_INFO_SUCCESS = 'FETCH_CURRENT_USER_INFO_SUCCESS';
export const FETCH_CURRENT_USER_INFO_ERROR = 'FETCH_CURRENT_USER_INFO_ERROR';
export const CHECK_RESET_PASSWORD_CODE_SUCCESS = 'CHECK_RESET_PASSWORD_CODE_SUCCESS';
export const CHECK_RESET_PASSWORD_CODE_ERROR = 'CHECK_RESET_PASSWORD_CODE_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_ERROR = 'FETCH_PROJECT_ERROR';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';

export const GET_MY_PROJECTS_SUCCESS = 'GET_MY_PROJECTS_SUCCESS';
export const GET_MY_PROJECTS_ERROR = 'GET_MY_PROJECTS_ERROR';

export const FETCH_SEARCH_AUTO_COMPLETE_SUCCESS = 'FETCH_SEARCH_AUTO_COMPLETE_SUCCESS';

export const FETCH_NEW_ADVANCE_SEARCH_RESULT_SUCCESS = 'FETCH_NEW_ADVANCE_SEARCH_RESULT_SUCCESS';
export const FETCH_MORE_ADVANCE_SEARCH_RESULT_SUCCESS = 'FETCH_MORE_ADVANCE_SEARCH_RESULT_SUCCESS';

export const FETCH_HIGHLIGHT_SUCCESS = 'FETCH_HIGHLIGHT_SUCCESS';
